defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

wandb:
  project: hyphen-detection
  entity: frederikschubert
  tags: []
  name: null

debug: false
fp16: true

train_loss_kwargs:
  target_threshold: 0.2
  smoothing: 0.1
optimizer_kwargs:
  opt: lookahead_AdamW
  lr: 1.0e-3
  weight_decay: 1.0e-3
scheduler_kwargs:
  warmup_epochs: 1
  max_epochs: ${epochs}
  eta_min: 1.0e-6
  warmup_start_lr: 1.0e-6

model_name: efficientnet_b3a
model_kwargs:
  in_chans: 4
  pretrained: true
num_classes: 2
batch_size: 100
epochs: 20

dataset:
  num_samples: 4
  subsample: true
  patch_size: 224
  val_split: 0.2
  input_dirs:
    - Ausz채hlung_1/CHILE
    - Ausz채hlung_1/Chile_New_Input_1
    - Ausz채hlung_1/ISRAEL
    - Ausz채hlung_1/Asendorf
    - Chile_Input_2
    - Chile_New_Input_2
  grid_files:
    - grid_20x17.csv
    - grid_20x17.csv
    - grid_20x17.csv
    - grid_23x17.csv
    - grid_20x17.csv
    - grid_20x17.csv
  input_dir_base: /home/schubert/projects/hyphen-detection/nobackup/data
  output_dir: /home/schubert/projects/hyphen-detection/nobackup/data_processed

hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
